## Basic Configuration
baseurl = "https://linksake.github.io/manzano/"
languageCode = "es-MX"
title = "Alejandro Manzano"
theme = "triple-hyde"

## Hugo Built-in Features
enableRobotsTXT = true
summarylength = 15

## Site Settings
[params]
author = "Alejandro Manzano"
title = "Alejandro Manzano"
dateformat = "2 Jan, 2006"
mainSections = ["posts"]
# description = "Escritor de ciencia-ficción"
# authorimage = "images/portait-1a.jpg"
relatedPosts = true
postNavigation = true

# sidebar, copyright & license
logoimage = "images/logos/3.png"
copyright = "Alejandro Manzano"
since = 2025
showBuiltWith = false

# highlightjs
highlightjs = false

## Social Accounts
[params.social]
instagram = "alejandroyid"
linkedin = "<username>"
facebook = "<username>"
email = "contacto@alejandromanzano.mx"
rss = "/manzano/index.xml/"

## Main Menu
[[menu.main]]
name = "Sobre mí"
identifier = "about"
weight = 50
url = "/about/"
[[menu.main]]
name = "Publicaciones"
weight = 100
identifier = "posts"
url = "/posts/"
[[menu.main]]
name = "Presentaciones"
weight = 150
identifier = "portfolio"
url = "/portfolio/"
[[menu.main]]
name = "Archivo Trastorno  ➝"
identifier = "AT"
weight = 200
url = "https://www.amazon.com.mx/Archivo-Trastorno-Colecci%C3%B3n-fragmentos-Spanish/dp/6078244663?ufe=app_do%3Aamzn1.fos.de93fa6a-174c-4df7-be7c-5bc8e9c5a71b"
[[menu.main]]
name = "The Pitch ➝"
identifier = "TP"
weight = 250
url = "https://alejandro-manzano.itch.io/the-pitch"
[[menu.main]]
name = "El Telar ➝"
identifier = "ET"
weight = 300
url = "https://eltelar.xyz/"
